### ISSUE TITLE
Optional addons

### ISSUE THREAD

**Issue by nathansamson** [Fri3dCamp/badge-2020#16]
During fri3d there was a talk with some extra details about HW
Will the slides be made available?

I am mostly interested in adding CO2 and temperature sensor (if I remember correctly that was mentioned)

Also I dont think it was mentioned in the slides, but some basic instructions on how to add them would be nice (eg for CO2 sensor I see that IO26 / IO15 should be used but I can't immediately find it on the physical layout)

**Comment by Brubacker** [comment]
Information regarding those parts and the presentation have been added to the repository.

**Comment by nathansamson** [comment]
Thanks for adding those

I am still missing the connected ports for the "Temperature and Humidity sensor" (which also isn't mentioned on the block diagram)



The docs for the CO2 sensor can also receive a little improvement (I would create a MR for this but I am not sure if I am correct)

"With the help of P5 and P8 SMD headers ... Alternatively, there is also room for the [Molex 53261-0771](https://www.molex.com/molex/products/part-detail/pcb_headers/0532610771) SMD connector"

Its not mentioned but I assume this alternative method is on the P9 connector (its the only one that seems to fit).
Is the P9 also connected to the same ports (IO26/IO15) or is it connected to other ports as well?

**Comment by Brubacker** [comment]
Which ports are you referring to? The Würth temperature and humidity sensor is connector to I²C (IO21 for SDA, IO22 for SCL) The address is included in the schematic (0x5F) 
If you prefer not to solder them, I would suggest looking at [Stemma QT ](https://www.adafruit.com/category/620) or [QWIIC](https://www.sparkfun.com/qwiic) sensors, those are also connected to the same I²C bus.

I have updated the the readme to include the reference to P9. 
Indeed, both connectors connect to the same pins (so you can't add two CO2 sensors)

**Comment by nathansamson** [comment]
![image](https://user-images.githubusercontent.com/93735/187618987-c456ff6e-5fe8-480f-8241-ce3720f46d39.png)

A) For me it wasn't clear the temp sensor correlated to the Stemma QT connector :) (Probably might need some clarification as well)
I already ordered the sensors to solder on so Ill have to visit a makerspace where I can try to solder it on :)

B) Now I realize its on the i2c bus I understand that I only need the address which would be part of the sensor spec and not specific to this board config. I also assume that most users actually  generally don't need to know this address since its coded in the arduino library (fun fact: I don't intend to use the arduino library so I probably would need to know this anyway, but I would then have found it myself).

Thanks for everything :)
